server:
  port: 9000

## Gateway Routes
spring:
  application:
    name: api-gateway
  cloud:
    circuitbreaker:
      resilience4j:
        enabled: true
    gateway:
      mvc:
        routes:
#          - id: booking-route
#            uri:
#              ${BOOKING_ROUTE_URI:http://localhost:8081}
#            predicates:
#              - Path=/bookings/**
#            filters:
#              - PrefixPath=/api/v1
#              - AddResponseHeader=X-Powered-By, IAM Gateway Service
#              - name: CircuitBreaker
#                args:
#                  id: bookingCircuitBreaker
#                  name: bookingCircuitBreaker
#                  fallbackUri: forward:/fallback
          - id: user-swagger-route
            uri:
              ${USER_ROUTE_URI:http://localhost:8080}
            predicates:
              - Path=/aggregate/user-service/api-docs # route path
            filters:
              - SetPath=/v3/api-docs # forwards to http://localhost:8080/v3/api-docs
          - id: booking-swagger-route
            uri:
              ${BOOKING_ROUTE_URI:http://localhost:8081}
            predicates:
              - Path=/aggregate/booking-service/api-docs
            filters:
              - SetPath=/v3/api-docs

  main:
    allow-bean-definition-overriding: true
springdoc:
  swagger-ui:
    path: /api-docs/swagger
    urls:
      - name: User Service
        url: /aggregate/user-service/api-docs
      - name: Booking Service
        url: /aggregate/booking-service/api-docs
  api-docs:
    path: /api-docs

## Actuator props
management:
  endpoints:
    web:
      exposure:
        include: health, metrics
  endpoint:
    health:
      show-details: always
      ## allow downstream apis to access the actuator of this api gateway
    gateway:
      enabled: true
  health:
    circuitbreakers:
      enabled: true

## Resilence4J props
resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-type: count_based
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
  timelimiter:
    configs:
      default:
        timeout-duration:
          seconds: 3
