apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-config
data:
  # RabbitMQ
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_MANAGEMENT_PORT: "15672"
  # Loki
  LOKI_URL: "http://loki.default.svc.cluster.local:3100/loki/api/v1/push"
  # Tempo
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://tempo.default.svc.cluster.local:9411"
  # User service
  USER_SERVICE_URL: "http://user-service.default.svc.cluster.local:8080"
  # Booking Service
  BOOKING_SERVICE_URL: "http://booking-service.default.svc.cluster.local:8081"
